### ISSUE TITLE
libbpf: failed to find skeleton map '.rodata.str1.1'

### ISSUE THREAD

**Issue by Xarlley** [masmullin2000/libbpf-sample#4]
I'm using 6.5 kernel on Ubuntu 22.04 server x86_64.
When compiling the kernel, I first:
make defconfig
then:
cat tools/testing/selftests/bpf/config >> .config
and, also add these at the ending of .config:
CONFIG_KPROBES=y
CONFIG_UPROBES=y
CONFIG_DEBUG_FS=y
CONFIG_FTRACE=y
CONFIG_FTRACE_SYSCALLS=y
CONFIG_KPROBE_EVENTS=y
CONFIG_UPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y
then,
make
make modules_install
make install

#####
I cloned your project.
cd c
cd simple
vim Makefile as:
#LINUX_KERNEL_DIR_MAINLINE=/code/mainline
#LINUX_KERNEL_DIR_STABLE=/code/linux-stable
LINUX_KERNEL_DIR_BPF_NEXT=/root/linux-6.5

/root/linux-6.5 is where the linux source code was put.

Then,
make run

I got this,
/root/linux-6.5/tools/bpf/bpftool/bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
clang -g -O3 -target bpf -D__TARGET_ARCH_x86_64 -c exec.bpf.c -o exec.bpf.o
/root/linux-6.5/tools/bpf/bpftool/bpftool gen skeleton exec.bpf.o name exec > exec.skel.h
clang exec.c -lbpf -lelf -o exec
sudo ./exec
libbpf: elf: skipping unrecognized data section(4) .rodata.str1.1
libbpf: failed to find skeleton map '.rodata.str1.1'
make: *** [Makefile:37: run] Segmentation fault

Could you please give a solution? I have no idea why it goes not well. I google about the log, and found nothing really working.
Thank you very much!

**Comment by Xarlley** [comment]
I run every thing as root.

**Comment by Xarlley** [comment]
I tried to imitate the practices mentioned in this page. This page seems to be saying that bpf_printk cannot be used?
https://lore.kernel.org/bpf/161731595664.74613.1603087410166945302.stgit@john-XPS-13-9370/T/
In other words, I commented out the bpf_printk function in exec.bpf.c. The make run command will no longer report errors. (Actually, this error comes from executing exec at the end of the Makefile. The result of executing exec directly on the command line is the same)

**Comment by masmullin2000** [comment]
There's probably something lacking from your .config.  I don't know what it is, but this is my guess.

Try the following in your /root/linux-6.5 dir

```
make menuconfig
```

Then go down to the bottom to "Kernel Hacking"

Then turn on "Kernel Debugging".  This turns on a bunch of different things.

Then recompile and retry.

If that doesn't work, get the config from your distribution (should be in /boot/config.somethingorother) and use that instead of the selftest config eg:

```
make mrproper
cp /boot/config.12345 > /.config
make -j<however_many_cores_you_have_times_2>
make modules_install
make install
```

**Comment by Xarlley** [comment]
I tried the two methods you mentioned to change the config. I found that the kernel debug option is turned on by default, whether it is 6.5 or 5.15 that comes with ubuntu22. Neither method worked. I mentioned the method of stopping using bpf_printk in my previous comment. It seems that this is the only way to avoid this error. Do you have any other way to print information? I think it is more important to find another way to print effectively than to solve this strange error.

**Comment by Xarlley** [comment]
Whether I appended the bpf self-test config to the end of the .config file before, or the method you mentioned using the config file under /boot, they can compile and run the program without the bpf_printk function normally.

**Comment by masmullin2000** [comment]
the bpf_printk issue is likely a symptom of a larger problem.  If you fix it, you'll probably run into future problems as you start to explore bpf deeper.  bpf_printk is a fundamental function that is used by nearly all developers writing libbpf programs.

Next thing to try is change the -O3 to a -O2 in the Makefile.  Thats a bit of a longshot, but give ti a try.

Last thing to try is simply run the distribution provided kernel instead of your custom kernel.  Ubuntu 22.04's kernel has all the BTF/BPF stuff you want.

NOTE: Years ago I was playing with a custom kernel doing BPF and ran into the bpf_printk issue similar to what you were seeing, but this was quite a while ago. I had screwed up something about the configuration, but I cannot remember what. I currently run a custom kernel on my ARM based laptop and have no issues running much more complicated BPF code than the sample.

**Comment by Xarlley** [comment]
First of all, please forgive me, I am an intern and may ask some simple and stupid questions. Thank you for your answer.
You mentioned changing O3 to O2. I looked for the Ox character in the Makefile under the root directory of the linux source code, and I found that there was no O3, and all parameters were O2. Does this mean that the default compilation optimization method is O2 and I don't need to make changes?

**Comment by Xarlley** [comment]
I used apt-cache search linux-source to find the following:
linux-source - Linux kernel source with Ubuntu patches
linux-source-5.15.0 - Linux kernel source for version 5.15.0 with Ubuntu patches
linux-source-5.19.0 - Linux kernel source for version 5.19.0 with Ubuntu patches
linux-source-6.2.0 - Linux kernel source for version 6.2.0 with Ubuntu patches
It seems that this is the Ubuntu-specific kernel. I downloaded the 5.15 version of the code. It is installed under /usr/src. I followed the steps of copying the config file under /boot to the source code and compiling the kernel normally, and got bpftool under /tools/bpf/bpftool. I specified the location of this bpftool in your project. Reporting errors doesn't make any difference, nothing changes.

**Comment by masmullin2000** [comment]
All of the LINUX_KERNEL_DIR stuff was added because Ubuntu 20.04 did not have BTF support until after this project was published.  Ubuntu 20.04 now has BTF support, and Ubuntu 22.04 was shipped with BTF support, so you do not need to compile a custom kernel.  You can use the kernel provided by the distribution.

You do not need any Kernel Source, you do not need to do any kernel compilation.  Just run the kernel that the Ubuntu Developers ship with their distribution.

I have just done the following

1) Installed a fresh ubuntu 22.04 server from the ISO (as a VM)
2) sudo apt update && sudo apt upgrade -y
3) reboot
4) uname -r -- 5.15.0-83-generic
5) sudo apt install make gcc clang linux-tools-common linux-tools-generic libbpf-dev
6) git clone https://github.com/masmullin2000/libbpf-sample.git
7) cd libbpf-sample/c/simple
8) edit the Makefile, comment away BPFTOOL=$(LINUX_KERNEL_DIR)/tools/bpf/bpftool/bpftool on line 17
9)
```
make run
bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
clang -g -O3 -target bpf -D__TARGET_ARCH_x86_64 -c exec.bpf.c -o exec.bpf.o
bpftool gen skeleton exec.bpf.o name exec > exec.skel.h
libbpf: elf: skipping unrecognized data section(4) .rodata.str1.1
clang exec.c -lbpf -lelf -o exec
sudo ./exec
libbpf: elf: skipping unrecognized data section(4) .rodata.str1.1
```

Program is running.
10) In another bash shell `sudo cat /sys/kernel/debug/tracing/trace_pipe`
11) Observe "bpf_trace_printk: Exec Called"

12) Kill make run command

**Comment by Xarlley** [comment]
Thank you very much for the how-to guide! I am so grateful for your patience!
I reproduced exactly what you did and it was successful.
I found that the key to solving the problem is to specify the path of bpftool to the bpftool provided by the system, rather than the bpftool under tool in the source code path. I've also had success on ubuntu where I compiled and installed the kernel myself. Thanks again for your answer.
